#!/bin/sh
set -e

run () {
    echo "# $@"
    "$@"
}

run cd "$(dirname "$0")/../schema/testdata"
[ -e schema-fuzz.zip ] || run go-fuzz-build chitin.io/chitin/schema
run go-fuzz -bin=schema-fuzz.zip -workdir=fuzz
